CREATE TABLE request_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    int1 INTEGER NOT NULL CHECK (int1 > 0),
    int2 INTEGER NOT NULL CHECK (int2 > 0),
    request_limit INTEGER NOT NULL CHECK (request_limit BETWEEN 1 AND 10000),
    str1 VARCHAR(100) NOT NULL CHECK (LENGTH(str1) > 0),
    str2 VARCHAR(100) NOT NULL CHECK (LENGTH(str2) > 0),
    hits BIGINT NOT NULL CHECK (hits > 0),
    first_requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_request_statistics_parameters
        UNIQUE (int1, int2, request_limit, str1, str2)
);

CREATE INDEX idx_request_statistics_most_used
    ON request_statistics (hits DESC, first_requested_at ASC, id ASC);
